# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 658f1e053e6cc80841d9e30fe694b3932fbb07f6b89eb15e108af359d7355bdad56a1d1284e5b30bfd4268922742b383c9fdde32a6a2eb2f364469a6fa0c5222

test:
  secret_key_base: 37a5af8115722b6e87dacd15a055a66cca2695266de9c6b31d06a2a5773e5cc2d3675dce6485de67e3b0bcda6fa439c34a3404043e9fde01e152b5de92d29504

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
